### PR TITLE
Remove grcui and grcuiapi and related components

### PR DESCRIPTION
**Pull request by KevinFCormier**
Signed-off-by: Kevin Cormier <kcormier@redhat.com>

https://github.com/stolostron/backlog/issues/20442

### CODE REVIEW

**Comment by KevinFCormier** [comment]
/cc @gparvin @ycao56 

It's probably worth reviewing the Role to see if you can remove any privileges that were only needed by the UI.

**Review by ycao56 — APPROVED** [review]

**Pull request merged**
